FROM maven:3.9-eclipse-temurin-21-alpine AS build
WORKDIR /usr/app
COPY . /usr/app
RUN mvn versions:set-property -Dproperty=project.version -DnewVersion=0.0.1 && \
    mvn package -Pdev -DskipTests

FROM maven:3.9-eclipse-temurin-21-alpine
WORKDIR /usr/app
ENV JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
COPY --from=build /usr/app/target/*.jar /usr/app/app.jar
CMD ["java", "-jar", "/usr/app/app.jar"]