#!/bin/sh

projectDir=$(git rev-parse --show-toplevel)

echo "*** Starting run checkstyle"

mvn checkstyle:check > /dev/null
checkstyleStatus=$?
mvn xml:transform > /dev/null

if [ $checkstyleStatus -ne 0 ]
then
    echo "*** Failed, has checkstyle issues!"
    echo "Check report. ${projectDir}/target/generated-resources/xml/xslt/checkstyle-result.html"

    case "$(uname -sr)" in
      CYGWIN*|MINGW*|MINGW32*|MSYS*)
        powershell -c "Invoke-Item ${projectDir}/target/generated-resources/xml/xslt/checkstyle-result.html"
        ;;
      *)
        open "${projectDir}/target/generated-resources/xml/xslt/checkstyle-result.html"
        ;;
    esac

    exit $checkstyleStatus
fi

echo "*** Succeeded, no checkstyle issues found"