@startuml

skinparam linetype ortho

title "Iced Latte Architecture - Component Diagram"

actor "User\nBrowser" as browser
component [CloudFlare] #darkorange

browser --> [CloudFlare] : Resolve DNS
[CloudFlare] --> browser

package "Iced Latte subnet" {

  component [balancer (nginx)] #forestgreen
  component [balancer (same)] #forestgreen
  component [Frontend (NextJS)] #white
  component [Backend (SpringBoot)] #yellowgreen
  component [DB (Postgres)] #steelblue


  browser --> [balancer (nginx)]
  [balancer (nginx)] --> [Frontend (NextJS)]
  [Frontend (NextJS)] --> [balancer (same)]
  [balancer (same)] --> [Backend (SpringBoot)]
  [Backend (SpringBoot)] --> [DB (Postgres)]
}

package "Grafana labs" {
component [Loki] #orange
component [Prometheus] #sandybrown

  [Backend (SpringBoot)] -down--> [Loki]
  [Backend (SpringBoot)] -down-> [Prometheus]
}

component [AWS S3 (pictures)] #tomato
component [Google auth] #skyblue

[Backend (SpringBoot)] -right-> [AWS S3 (pictures)]
[Backend (SpringBoot)] .right.> [Google auth]



@enduml